### ISSUE TITLE
getting error when adding this library

### ISSUE THREAD

**Issue by santhoshrao519** [Mohammed-Alaa/GifLoading#2]
please checkk

**Comment by MohammedAlaaMorsi** [comment]
@santhoshrao519 What are the error exactly so I can Figure the issue,ex what targetSdk you use ?

**Comment by MohammedAlaaMorsi** [comment]
@santhoshrao519 You can also share your sample so I can Help

**Comment by santhoshrao519** [comment]
I'm getting followig error while syncing with library,
Error:(1304, 5) error: duplicate value for resource 'attr/src' with config ''.
Error:(1304, 5) error: resource previously defined here.

**Comment by MohammedAlaaMorsi** [comment]
@santhoshrao519 You can now check the latest version [1.0.2](https://github.com/Mohammed-Alaa/GifLoading/releases/tag/1.0.2) it has the quick fix for this issue put `app:srcImg="@drawable/your_gif"`, keep in mind that I will make some improvement in code when I have time. also let me know if your issue have been solved to close this issue also if you have other issues don't mind posting it
