### ISSUE TITLE
I'm getting this error after sync gradle.

### ISSUE THREAD

**Issue by DevMensIT** [Mohammed-Alaa/GifLoading#3]
ERROR: Failed to resolve: com.github.Mohammed-Alaa:GifLoading:1.0.2

**Comment by MohammedAlaaMorsi** [comment]
@kishan2212 did you follow [Step1](https://github.com/Mohammed-Alaa/GifLoading#step-1)

**Comment by MohammedAlaaMorsi** [comment]
@kishan2212 I think there is a problem with [jitpack](https://jitpack.io) repositories

**Comment by DevMensIT** [comment]
Yes i put jitpack repository

**Comment by MohammedAlaaMorsi** [comment]
you can download the code and import the **gifloading** module from file ->new -> import module
then put   `implementation project(':gifloading')` in app build.gradle  , till the problem with [jitpack ](https://jitpack.io/)is solved
